[tool.poetry]
name = "target-woocommerce"
version = "0.0.3"
description = "`target-woocommerce` is a Singer target for WooCommerce, built with the Meltano SDK for Singer Targets."
authors = ["arthur hotglue"]
keywords = [
    "ELT",
    "WooCommerce",
]
license = "Apache 2.0"

[tool.poetry.dependencies]
python = "<3.11,>=3.7.1"
requests = "^2.25.1"
singer-sdk = "^0.9.0"
random-user-agent = "^1.0.1"
"backports.cached-property" = "^1.0.1"
hotglue-models-ecommerce = { git = "https://gitlab.com/hotglue/hotglue-models-ecommerce.git", branch = "main"}

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
tox = "^3.24.4"
flake8 = "^3.9.2"
black = "^21.9b0"
pydocstyle = "^6.1.1"
mypy = "^0.910"
types-requests = "^2.26.1"
isort = "^5.10.1"

[tool.isort]
profile = "black"
multi_line_output = 3 # Vertical Hanging Indent
src_paths = "target_woocommerce"

[build-system]
requires = ["poetry-core==1.0.8"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
# CLI declaration
target-woocommerce-v2 = 'target_woocommerce.target:TargetWooCommerce.cli'
